### ISSUE TITLE
Issue with relative path of jQuery

### ISSUE THREAD

**Issue by chvonrohr** [pixelant/frontend_editing#101]
I had to change the jQuery path in ContentPostProc, as there was no leading slash:
https://github.com/pixelant/frontend_editing/blob/master/Classes/Hook/ContentPostProc.php#L174

btw: Inline editing is not working for me. Should I use a different branch than master or is this not implemented yet?

**Comment by MattiasNilsson** [comment]
Hi @chvonrohr How do you mean do not work yet? If you are using fluid templates you need to add a viewhelper for the content elements: https://pixelant.gitbooks.io/typo3-frontend-editing/content/gitbook/inline_editing/inline_editing.html

**Comment by chvonrohr** [comment]
hey, thanks for the fix.
oh, didn't get it with the helpers. works now perfectly, thx
