### ISSUE TITLE
No static template available

### ISSUE THREAD

**Issue by wowawebdesign** [pixelant/frontend_editing#81]
I wanted to test the new frontend editor in a very small test environment with TYPO3 8.5.0-dev. I cloned the extension and activated it in the EM.
But there is no static template which I could include in my TS template, see attached screenshot. 
Any ideas?
![2016-11-10_07-17-44](https://cloud.githubusercontent.com/assets/343511/20166583/163e44a8-a716-11e6-942c-3dc3fa910566.png)

**Comment by MattiasNilsson** [comment]
Hi @wowawebdesign ,

I just set up a TYPO3 installation with the latest dev-master and this is now it looks:

<img width="193" alt="skarmavbild 2016-11-10 kl 07 29 27" src="https://cloud.githubusercontent.com/assets/1718315/20166803/925b49fe-a717-11e6-9135-8488557d62a5.png">

<img width="1039" alt="skarmavbild 2016-11-10 kl 07 29 20" src="https://cloud.githubusercontent.com/assets/1718315/20166806/97d1c5fc-a717-11e6-9ff9-deb5bc159607.png">

Maybe is has something to do with the cache and TCA/Overrides?

**Comment by wowawebdesign** [comment]
Hm, I cleard the cache (incl. OPCode Cache) multiple times. TCA/Overrides: I don't think so, it's a clear, fresh installation without any third party extensions.

**Comment by wowawebdesign** [comment]
Oh fuck, I'm such an idiot! I close this issue! I activated the wrong extension in the EM! 
Sorry, and thank you for your quick reply!
