### ISSUE TITLE
Compatibility with TYPO3 7.6 

### ISSUE THREAD

**Issue by mhirdes** [pixelant/frontend_editing#82]
Hi everyone.

I wanted to test the extension in our dummy TYPO3 7.6 system. After installation and the steps of the documentation I got this error in the frontend:

Call to undefined method TYPO3\CMS\Fluid\View\StandaloneView::getRenderingContext() in /var/www/html/projekte/00_Entwicklung/typodummy/typo3_7_6/typo3conf/ext/frontend_editing/Classes/Hook/ContentPostProc.php

If I comment this line out, I get a new error:
PHP Warning: filemtime(): stat failed for EXT:frontend_editing/Resources/Private/Templates/Toolbars/Toolbars.html in /var/www/html/projekte/00_Entwicklung/typodummy/typo3_7_6/_sources/typo3_src-7.6.12/typo3/sysext/fluid/Classes/View/StandaloneView.php line 553

Is the extension maybe currently not compatible with 7.6?

Kind Regards,
Marc

**Comment by M-arcus** [comment]
From http://www.pixelant.net/crowdfunding/:

> Phase 9 - Backport to TYPO3 7.6 LTS
> 
> Deadline: April 3rd 2017

When the main functionality is done, there will be work on the comaptibility.

**Comment by MattiasNilsson** [comment]
@mhirdes Thanks for your feedback! Currently we are just supporting TYPO3 8.3 and above as you can see in the requirements. But we will have a phase in april 2017 when we are doing the backporting.

**Comment by Oktopuce** [comment]
**@mhirdes** : I've made some changes which have been integrated in the extension and now it's compatible with Typo3 7.6.

**Comment by mhirdes** [comment]
Thanks. I didn't read the roadmap, sry.
