### ISSUE TITLE
Saving changes to multiple fields of same element

### ISSUE THREAD

**Issue by jozefspisiak** [pixelant/frontend_editing#93]
When two different fields are editable, only change made to the last field is persisted into database when saved. Might be something to do how the changed are being tracked for each content element.

**Comment by phathoang** [comment]
@jozefspisiak I started to fix it on [fix-save-all-fields](https://github.com/pixelant/frontend_editing/tree/fix-save-all-fields) branch but didn't complete it, check 0cc5d0f.
The main issue is that the controller can only save 1 field at a time and I changed it. But then I went to check how Aloha did it and it is also saving 1 field at a time, or it's staging it somewhere, right after you finish editing the field. So I thought that if we will do something similar, then then my fix so the controller can save multiple fields is not needed.
